name: alcov-nooks-crannies
channels:
  - bioconda
  - defaults
dependencies:
  - bz2file=0.98
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - certifi=2022.12.7
  - cutadapt=2.6
  - dnaio=0.3
  - k8=0.2.5
  - krb5=1.19.2
  - minimap2=2.22
  - ncurses=6.2
  - openssl=1.1.1w
  - pigz=2.6
  - pip=22.3.1
  - python=3.7.3
  - readline=7.0
  - samtools
  - setuptools=65.6.3
  - sqlite=3.33.0
  - tk=8.6.14
  - wheel=0.38.4
  - xopen=0.7.3
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - bio==1.6.2
      - biopython==1.81
      - biothings-client==0.3.1
      - charset-normalizer==3.3.2
      - cycler==0.11.0
      - fire==0.6.0
      - fonttools==4.38.0
      - gprofiler-official==1.0.0
      - idna==3.10
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.5.3
      - mygene==3.2.2
      - numpy==1.21.6
      - ortools==9.5.2237
      - packaging==24.0
      - pandas==1.3.5
      - pillow==9.5.0
      - platformdirs==4.0.0
      - pooch==1.8.2
      - protobuf==4.24.4
      - pyparsing==3.1.4
      - pysam==0.22.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - requests==2.31.0
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.12.2
      - six==1.16.0
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - tqdm==4.66.5
      - typing-extensions==4.7.1
      - urllib3==2.0.7
